stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/creditcard.csv
  train:
      cmd: python src/train.py
      deps:
      - src/train.py
      - data/creditcard.csv
      metrics:
        - data/metrics.json:
            cache: false
