stages:
  download_data:
    cmd: python src/get_data.py
    deps:
      - src/download_dataset.py
    outs:
      - data/creditcard.csv
  train_clf:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/creditcard.csv
    outs:
      - data/confusion_matrix.png
      - data/model.pickle
    metrics:
      - data/metrics.json:
          cache: false
