channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cython=0.29.24
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - matplotlib=3.4.3
  - numpy=1.20.3
  - pandas=1.3.2
  - pillow=8.3.1
  - pip=21.0.1
  - pysocks=1.7.1
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyyaml=5.4.1
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tensorboard=2.5.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.5.0
  - tornado=6.1
  - urllib3=1.26.6
  - werkzeug=1.0.1
  - wheel=0.37.0
  - yaml=0.2.5