name: credit-fraud-detection-flow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CML Run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install Dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          pwd
          ls -lah

          # run-cache and reproduce pipeline
          dvc repro

          # Report metrics
          git fetch --prune
          echo "## Metrics: Workspace vs. Main"
          dvc metrics diff --show-md master > report.md